version: "3"
services:
  redis_1:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.2
  redis_2:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.3
  redis_3:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.4
  redis_4:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.5
  redis_5:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.6
  redis_6:
    build: ./redis
    networks:
      redis_cluster_network:
        ipv4_address: 172.19.197.7

  cluster_initializer:
    build:
      context: ./initializer
      dockerfile: ./initializer.dockerfile
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      - redis_cluster_network

  prometheus:
    build: ./prometheus
    ports:
      - 9090:9090
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
      - redis_exporter
    networks:
      - redis_cluster_network
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - redis_cluster_network
  redis_exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    command:
      - '--redis.addr='
    networks:
      - redis_cluster_network

networks:
  redis_cluster_network:
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
      - subnet: 172.19.197.1/24
